#! /bin/sh
# /etc/init.d/fastcamd
#

# Some things that run always
touch /var/lock/fastcamd

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    rm -f /tmp/raspifastcamd.pid
    /home/pi/otto-sdk/fastcmd/start_camd.sh
    ;;
  stop)
    /home/pi/otto-sdk/fastcmd/stop_camd.sh
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0

