#! /bin/sh
# /etc/init.d/python
#

# Some things that run always
touch /var/lock/python

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    cd /home/pi/otto-sdk/python/ ; server.py
    ;;
  stop)
	killall python
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0

