#! /bin/sh
# /etc/init.d/wifi
#

# Some things that run always
touch /var/lock/wifi
CREATE_AP=/home/pi/otto-sdk/vendor/tools/create_ap/create_ap
MAC=`cat /sys/class/net/wlan0/address | sed s/://g`

# Carry out specific functions when asked to by the system
case "$1" in
  start)
        $CREATE_AP -n --driver rtl871xdrv wlan0 OTTOClear-$MAC allyourbase
    ;;
  stop)
	killall hostapd
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0

